version: '3.7'
services:
  es:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ELK_VERSION: 7.15.2
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=cookie
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge